/* ─── FREE RESOURCE LIBRARY — always-on content ───
   The /materials page used to be 100% Firestore-driven, so it showed
   an empty shell until someone uploaded a file. This library gives it
   real substance on day one; anything the admin uploads is merged in
   on top.

   Every external link here was checked to resolve (HTTP 200) before
   shipping. Only official / first-party sources — no scraped PDFs,
   no copyright-shady mirrors. */

export const CATEGORIES = ['All', 'SAT & Abroad', 'NDA', 'JEE', 'NEET', 'Boards & HP TET']

/* Our own branded material — written here, sealed, hosted by us.
   Generated by scripts/make_materials.py into /public/materials. */
export const OUR_DOWNLOADS = [
  {
    id: 'sat-blueprint',
    category: 'SAT & Abroad',
    emoji: '📘',
    title: 'The SAT Blueprint',
    description:
      'Our full 7-page guide: the Digital SAT format, the Desmos strategy, the scholarship maths, a 10-week roadmap to 1400+, and every 2026–27 test date. Written by the mentor who scored 1540.',
    meta: '7 pages · PDF · free',
    href: '/brochure/Vision-Success-SAT-Blueprint.pdf',
    badge: 'FLAGSHIP',
  },
  {
    id: 'sat-card',
    category: 'SAT & Abroad',
    emoji: '🌍',
    title: 'Digital SAT — Command Card',
    description:
      'Every Math formula the SAT can ask you, the four Desmos moves that turn 40-second questions into 8-second ones, and the Reading & Writing traps the College Board reuses. Print it, pin it.',
    meta: '4 pages · PDF · free',
    href: '/materials/SAT-Command-Card.pdf',
    badge: 'NEW',
  },
  {
    id: 'nda-card',
    category: 'NDA',
    emoji: '🎖️',
    title: 'NDA Written — Command Card',
    description:
      'The full 1800-mark structure, the −1/3 rule most aspirants ignore, the Mathematics formulae that carry the 300-mark paper, and why GAT (600 marks) is where selections are quietly won.',
    meta: '4 pages · PDF · free',
    href: '/materials/NDA-Command-Card.pdf',
    badge: 'NEW',
  },
  {
    id: 'neet-card',
    category: 'NEET',
    emoji: '🩺',
    title: 'NEET UG — Command Card',
    description:
      'Where the 720 actually comes from, the +4/−1 discipline that separates 550 from 650, the high-yield NCERT Biology units, and the Physics formulae you cannot afford to look up.',
    meta: '4 pages · PDF · free',
    href: '/materials/NEET-Command-Card.pdf',
    badge: 'NEW',
  },
  {
    id: 'jee-card',
    category: 'JEE',
    emoji: '⚙️',
    title: 'JEE Main — Command Card',
    description:
      'The exact paper structure, the two-session rule most aspirants waste, the elimination economics of +4/−1, and the core Physics, Chemistry and Maths formulae on one card.',
    meta: '4 pages · PDF · free',
    href: '/materials/JEE-Command-Card.pdf',
    badge: 'NEW',
  },
]

/* Free tools on this site — genuinely useful, no sign-up to try */
export const OUR_TOOLS = [
  {
    id: 'predictor',
    category: 'SAT & Abroad',
    emoji: '🎯',
    title: 'SAT Score Predictor',
    description: 'Three sliders, ten seconds, an honest predicted range and a week-by-week plan to close the gap.',
    action: 'Try the tool',
    href: '/#blueprint',
  },
  {
    id: 'warclock',
    category: 'SAT & Abroad',
    emoji: '🕐',
    title: 'Live SAT Countdown & All 8 Dates',
    description: 'Official College Board 2026–27 calendar with a live countdown and every registration deadline.',
    action: 'See the dates',
    href: '/sat',
  },
  {
    id: 'quiz',
    category: 'All',
    emoji: '🧭',
    title: '“Which Exam Suits Me?” Quiz',
    description: 'Not sure whether it is NDA, NEET, JEE or abroad? Four questions and an honest verdict.',
    action: 'Take the quiz',
    href: '/start',
  },
]

/* Accurate, high-yield exam facts — the stuff students actually
   need pinned above their desk. Sourced from the official bodies. */
export const CHEAT_SHEETS = [
  {
    id: 'cs-sat',
    category: 'SAT & Abroad',
    emoji: '🌍',
    title: 'Digital SAT — the whole exam on one card',
    rows: [
      ['Format', '2 sections · 98 questions · 2 hr 14 min · on a laptop'],
      ['Reading & Writing', '54 questions · 64 min (two 32-min modules)'],
      ['Math', '44 questions · 70 min (two 35-min modules)'],
      ['Scoring', '400–1600 · NO negative marking'],
      ['Adaptive', 'Module 1 performance sets Module 2 difficulty'],
      ['Calculator', 'Built-in Desmos, allowed for ALL of Math'],
    ],
    tip: 'No negative marking means never leave a blank. In the last 30 seconds, fill every remaining bubble — statistically free marks.',
    more: { label: 'Full SAT playbook', href: '/enroll/sat' },
  },
  {
    id: 'cs-nda',
    category: 'NDA',
    emoji: '🎖️',
    title: 'NDA (UPSC) — marks, marking, and the real weightage',
    rows: [
      ['Paper 1 — Mathematics', '300 marks · 120 questions · 2.5 hrs'],
      ['Paper 2 — GAT', '600 marks · 150 questions · 2.5 hrs'],
      ['GAT split', 'English 200 + General Knowledge 400'],
      ['Negative marking', '−1/3 of the marks for each wrong answer'],
      ['SSB Interview', '900 marks · 5-day process'],
      ['Frequency', 'Twice a year (NDA I and NDA II)'],
    ],
    tip: 'Everyone grinds Maths (300) and ignores GAT (600). English alone is 200 marks you can bank in weeks — that is where selections are quietly won.',
    more: { label: 'Full NDA playbook', href: '/enroll/nda' },
  },
  {
    id: 'cs-neet',
    category: 'NEET',
    emoji: '🩺',
    title: 'NEET (NTA) — where the 720 actually comes from',
    rows: [
      ['Total', '180 questions · 720 marks'],
      ['Physics', '45 questions · 180 marks'],
      ['Chemistry', '45 questions · 180 marks'],
      ['Biology (Botany + Zoology)', '90 questions · 360 marks'],
      ['Marking', '+4 correct · −1 wrong'],
      ['Source', 'NCERT-dominant, Class 11 + 12 syllabus'],
    ],
    tip: 'Half the paper is one subject. Biology is 360 of 720 and maps almost line-for-line onto NCERT — read it twice before you touch any reference book.',
    more: { label: 'Full NEET playbook', href: '/enroll/neet' },
  },
  {
    id: 'cs-jee',
    category: 'JEE',
    emoji: '⚙️',
    title: 'JEE Main (NTA) — the format in six lines',
    rows: [
      ['Format', 'Computer-based · 75 questions · 300 marks · 3 hrs'],
      ['Per subject', 'Physics / Chemistry / Maths — 25 each (20 MCQ + 5 numerical)'],
      ['Marking', '+4 correct · −1 wrong'],
      ['Sessions', 'Twice a year (January + April) — your BEST score counts'],
      ['Next level', 'Top ~2.5 lakh qualify for JEE Advanced (IITs)'],
      ['Boards rule', '75% in Class 12 (or top-20 percentile) for NIT/IIIT seats'],
    ],
    tip: 'Because only your best session counts, the January attempt is a free rehearsal with real stakes. Sit it even at 70% preparation.',
    more: { label: 'Full JEE playbook', href: '/enroll/jee' },
  },
]

/* Official, free, first-party sources. All verified to resolve. */
export const OFFICIAL_LINKS = [
  {
    category: 'SAT & Abroad',
    emoji: '🏛️',
    title: 'College Board — Official SAT Practice',
    description: 'Full-length official practice tests and the Bluebook app, straight from the exam makers. Free.',
    href: 'https://satsuite.collegeboard.org/sat/practice-preparation',
  },
  {
    category: 'SAT & Abroad',
    emoji: '📺',
    title: 'Khan Academy — Official SAT Prep',
    description: 'The College Board’s official free practice partner. Thousands of practice questions, no fee, ever.',
    href: 'https://www.khanacademy.org/sat',
  },
  {
    category: 'SAT & Abroad',
    emoji: '🗣️',
    title: 'IELTS — Official Site',
    description: 'Test format, free sample questions and band descriptors from the official IELTS partners.',
    href: 'https://ielts.org',
  },
  {
    category: 'JEE',
    emoji: '📋',
    title: 'NTA — JEE Main Official Portal',
    description: 'Notifications, syllabus, information bulletin, and previous-year question papers. Always check dates here first.',
    href: 'https://jeemain.nta.nic.in',
  },
  {
    category: 'NEET',
    emoji: '📋',
    title: 'NTA — NEET UG Official Portal',
    description: 'Official notifications, syllabus, information bulletin and past papers for NEET UG.',
    href: 'https://neet.nta.nic.in',
  },
  {
    category: 'NDA',
    emoji: '🇮🇳',
    title: 'UPSC — Official Site',
    description: 'The only place NDA notifications, exam dates and previous-year papers are officially released.',
    href: 'https://upsc.gov.in',
  },
  {
    category: 'Boards & HP TET',
    emoji: '🏔️',
    title: 'HPBOSE — HP Board & HP TET',
    description: 'Himachal Pradesh Board: datesheets, syllabus, results, and HP TET notifications (HPBOSE conducts the TET).',
    href: 'https://hpbose.org',
  },
  {
    category: 'Boards & HP TET',
    emoji: '📚',
    title: 'NCERT — Free Official Textbooks',
    description: 'Every NCERT textbook, free and legal, from the official source. The backbone of NEET, JEE and boards.',
    href: 'https://ncert.nic.in',
  },
]
