/* ─── 18 SEO landing pages (developer brief, Section E) ───
   Rendered by app/[slug]/page.js as fully static server pages.
   Each page: keyword H1, intro, coverage, why-us, fee, 5 FAQs,
   internal links, WhatsApp CTAs, map embed, Course/FAQ schema. */

const WHY_US_BASE = [
  'Taught by an NIT Hamirpur alumnus — concept-first teaching, not rote learning',
  'Small batches (max 15 students) — every doubt gets heard and solved',
  'Weekly tests with detailed analysis and parent progress updates',
  'Bilingual teaching (Hindi + English) — concepts explained until they click',
  'Free demo class before you pay a single rupee',
  '4.9★ Google rating and 90%+ board results from our students',
]

const FEE_NOTE =
  'Fees are never a barrier at Vision Success — they are always negotiated based on your ability and financial situation. Come talk to us first.'

export const SEO_PAGES = [
  {
    slug: 'physics-coaching-una',
    seoTitle: 'Best Physics Coaching in Una HP | Class 11 & 12',
    metaDescription:
      'Expert Physics coaching in Una, HP for Class 11 & 12, JEE and NEET. NIT Hamirpur faculty, small batches, weekly tests. Free demo class — call or WhatsApp now.',
    h1: 'Physics Coaching in Una, Himachal Pradesh',
    emoji: '⚡',
    courseName: 'Physics Coaching in Una — Class 11 & 12',
    intro: [
      'Looking for physics coaching in Una that actually makes physics make sense? At Vision Success Coaching Institute, physics is taught from concepts — not formulas to memorize. Every law, every derivation, every numerical is built up step by step until you can solve problems on your own.',
      'Our physics coaching in Una covers Class 11 and Class 12 (CBSE and HP Board) along with JEE and NEET-level problem solving. Students from Una, Amb, Bangana, Haroli, Daulatpur, and Mehatpur attend our small-batch classes.',
    ],
    covers: [
      'Mechanics — Kinematics, Laws of Motion, Work-Energy, Rotation',
      'Electricity & Magnetism — Electrostatics, Current, EMI',
      'Optics — Ray Optics and Wave Optics',
      'Thermodynamics & Kinetic Theory',
      'Modern Physics — Atoms, Nuclei, Semiconductors',
      'Waves & Oscillations',
      'Complete NCERT + board sample papers',
      'JEE Mains & NEET level numericals',
    ],
    fee: 'Class 11–12 Physics: typically ₹2,000–₹3,500/month.',
    faqs: [
      { q: 'Is there Physics coaching available in Una?', a: 'Yes — Vision Success Coaching Institute in Una offers Physics coaching for Class 11 and Class 12. We cover the complete NCERT syllabus with JEE and NEET-level problem solving.' },
      { q: 'Who teaches Physics at Vision Success?', a: 'Physics is taught by NIT Hamirpur-trained faculty using a concept-first method — theory, derivations, and then graded numericals in every class.' },
      { q: 'Do you prepare for both boards and JEE/NEET Physics?', a: 'Yes. The core syllabus is the same — we teach concepts once, then layer board-style answer writing and JEE/NEET-style problem solving on top.' },
      { q: 'What are the batch timings for Physics coaching?', a: 'After-school batches run in the evening for school students, with separate morning slots for droppers. WhatsApp us for the current timetable.' },
      { q: 'Is a free demo Physics class available?', a: 'Yes — attend a free demo class before paying anything. Call or WhatsApp us to book your slot.' },
    ],
    related: [
      { href: '/chemistry-coaching-una', label: 'Chemistry Coaching in Una' },
      { href: '/class-11-coaching-una', label: 'Class 11 Science Coaching' },
      { href: '/jee-coaching-una', label: 'JEE Coaching in Una' },
      { href: '/neet-coaching-una', label: 'NEET Coaching in Una' },
    ],
  },
  {
    slug: 'chemistry-coaching-una',
    seoTitle: 'Best Chemistry Coaching in Una HP | All 3 Branches',
    metaDescription:
      'Chemistry coaching in Una — Physical, Organic & Inorganic for Class 11, 12, JEE & NEET. NCERT-focused, small batches, weekly tests. Free demo class available.',
    h1: 'Chemistry Coaching in Una, Himachal Pradesh',
    emoji: '🧪',
    courseName: 'Chemistry Coaching in Una — Physical, Organic, Inorganic',
    intro: [
      'Chemistry has three personalities — Physical needs maths, Organic needs logic, Inorganic needs smart memory techniques. Our chemistry coaching in Una teaches each branch the way it deserves, so no part of the syllabus stays scary.',
      'We cover Class 11 and 12 chemistry for CBSE and HP Board, fully integrated with NEET and JEE preparation. NCERT is our backbone — because that is exactly where boards, NEET, and JEE questions come from.',
    ],
    covers: [
      'Physical Chemistry — Mole Concept, Equilibrium, Thermodynamics, Electrochemistry',
      'Organic Chemistry — GOC, Hydrocarbons, Named Reactions, Mechanisms',
      'Inorganic Chemistry — Periodic Table, Bonding, Coordination Compounds',
      'NCERT line-by-line coverage (critical for NEET)',
      'Board answer-writing practice & sample papers',
      'JEE & NEET previous year questions, chapter-wise',
    ],
    fee: 'Class 11–12 Chemistry: typically ₹2,000–₹3,500/month.',
    faqs: [
      { q: 'Do you offer Chemistry coaching in Una?', a: 'Yes — we offer Chemistry coaching covering Physical, Organic, and Inorganic branches for Class 11 and 12 in Una, Himachal Pradesh. Both CBSE and HP Board students are welcome.' },
      { q: 'Is Organic Chemistry taught from basics?', a: 'Yes. We start from General Organic Chemistry (GOC) fundamentals so reactions become logic, not memorisation. Most students find Organic becomes their favourite branch.' },
      { q: 'Is this useful for NEET and JEE too?', a: 'Absolutely — our chemistry classes integrate NEET and JEE question practice with board preparation, since the syllabus is shared.' },
      { q: 'How important is NCERT for Chemistry?', a: 'Extremely — a large share of NEET and board chemistry questions come straight from NCERT. We cover it line by line, with extra practice on top.' },
      { q: 'Can I join for Chemistry alone?', a: 'Yes, single-subject enrollment is available. Many students join us just for Chemistry or Physics alongside school.' },
    ],
    related: [
      { href: '/physics-coaching-una', label: 'Physics Coaching in Una' },
      { href: '/biology-coaching-una', label: 'Biology Coaching in Una' },
      { href: '/neet-coaching-una', label: 'NEET Coaching in Una' },
    ],
  },
  {
    slug: 'biology-coaching-una',
    seoTitle: 'Best Biology Coaching in Una HP | NEET Preparation',
    metaDescription:
      'Biology coaching in Una — Botany & Zoology for Class 11, 12 and NEET. Diagram-based NCERT teaching, small batches, weekly tests. Book a free demo class today.',
    h1: 'Biology Coaching in Una — Botany, Zoology & NEET Preparation',
    emoji: '🧬',
    courseName: 'Biology Coaching in Una — NEET Preparation',
    intro: [
      'Biology is the highest-scoring subject in NEET — 360 of 720 marks. Our biology coaching in Una is built around diagram-based NCERT mastery, because that is where the vast majority of NEET Biology questions come from.',
      'We teach Botany and Zoology for Class 11 and 12 (CBSE and HP Board) with NEET-pattern MCQ practice in every week of the course.',
    ],
    covers: [
      'Botany — Plant Physiology, Genetics, Ecology, Cell Biology',
      'Zoology — Human Physiology, Reproduction, Evolution',
      'NCERT line-by-line with diagram practice',
      'NEET-pattern MCQs and previous year questions',
      'Board answer-writing and diagram presentation',
      'Weekly tests with detailed analysis',
    ],
    fee: 'Class 11–12 Biology: typically ₹2,000–₹3,500/month.',
    faqs: [
      { q: 'Is Biology coaching available in Una?', a: 'Yes — Vision Success offers Biology coaching (Botany + Zoology) for Class 11, Class 12, and NEET preparation in Una, Himachal Pradesh.' },
      { q: 'How is Biology taught for NEET?', a: 'NCERT-first and diagram-based. Most NEET Biology questions map directly to NCERT lines and figures — we make sure you know them cold, then drill MCQs.' },
      { q: 'Can board students join without NEET plans?', a: 'Of course. Board-focused students get answer-writing and diagram practice for full marks in HPBOSE/CBSE exams.' },
      { q: 'How many marks is Biology worth in NEET?', a: 'Biology is 360 of 720 marks — half the exam. Strong Biology alone can carry your NEET rank a very long way.' },
      { q: 'Is there a demo class for Biology?', a: 'Yes — your first class is a free demo. WhatsApp or call us to book it.' },
    ],
    related: [
      { href: '/chemistry-coaching-una', label: 'Chemistry Coaching in Una' },
      { href: '/neet-coaching-una', label: 'NEET Coaching in Una' },
      { href: '/class-11-coaching-una', label: 'Class 11 Science Coaching' },
    ],
  },
  {
    slug: 'maths-coaching-una',
    seoTitle: 'Best Maths Coaching in Una HP | NIT Expert Faculty',
    metaDescription:
      'Maths coaching in Una by NIT Hamirpur alumnus. Class 10, 11, 12, JEE & NDA mathematics with shortcut techniques and weekly tests. Free demo class — book now.',
    h1: 'Mathematics Coaching in Una, Himachal Pradesh',
    emoji: '📐',
    courseName: 'Mathematics Coaching in Una — NIT Expert',
    intro: [
      'Maths is our home ground. Vision Success was built by an NIT Hamirpur alumnus who believes every student can be good at maths — if it is taught with logic, patterns, and the right shortcuts instead of fear.',
      'Our maths coaching in Una covers Class 10, 11, and 12 (CBSE + HP Board), plus JEE Mains and the NDA written exam — where mathematics alone is worth 300 marks.',
    ],
    covers: [
      'Class 10 — full board syllabus + basics strengthening',
      'Class 11–12 — Algebra, Calculus, Coordinate Geometry, Trigonometry, Vectors',
      'JEE Mains level problem solving',
      'NDA Maths — complete 300-mark written syllabus',
      'Shortcut techniques and speed calculation tricks',
      'Weekly tests, previous year papers, doubt sessions',
    ],
    fee: 'Class 10: ₹1,500–₹2,000/month · Class 11–12: ₹2,000–₹3,500/month · JEE/NDA level: ₹3,000–₹5,000/month.',
    faqs: [
      { q: 'Who teaches Maths at Vision Success Una?', a: 'Mathematics is taught by an NIT Hamirpur alumnus — with concept-building, pattern recognition, and exam shortcuts developed over 13+ years of teaching.' },
      { q: 'Which classes are covered in Maths coaching?', a: 'Class 10, 11, and 12 for CBSE and HP Board, plus dedicated JEE Mains and NDA written exam mathematics.' },
      { q: 'My child is weak in Maths. Can you help?', a: 'That is our speciality. We restart from wherever the gaps are — even previous-class basics — and rebuild confidence with small wins every week.' },
      { q: 'Do you teach NDA-level Maths?', a: 'Yes — NDA Maths (300 marks of the written exam) is our flagship strength, with shortcut techniques and previous year paper practice.' },
      { q: 'What is the fee for Maths coaching in Una?', a: 'Roughly ₹1,500–₹3,500/month depending on class and course — and fees are always negotiated based on ability. No capable student is turned away.' },
    ],
    related: [
      { href: '/nda-coaching-una', label: 'NDA Coaching in Una' },
      { href: '/jee-coaching-una', label: 'JEE Coaching in Una' },
      { href: '/class-10-coaching-una', label: 'Class 10 Coaching in Una' },
    ],
  },
  {
    slug: 'nda-coaching-una',
    seoTitle: 'NDA Coaching in Una HP | NDA Maths Expert',
    metaDescription:
      'NDA coaching in Una, HP — complete written exam (Maths + GAT) and SSB preparation. NIT faculty, previous year papers, mock tests. Free demo class available.',
    h1: 'NDA Coaching in Una, Himachal Pradesh — Written Exam Maths Expert',
    emoji: '🎖️',
    courseName: 'NDA Coaching in Una — Written Exam + SSB',
    intro: [
      'NDA is our flagship. Vision Success has trained 7+ students who now serve as officers, and our NDA coaching in Una is built around the two things that decide selection: the 900-mark written exam and the 900-mark SSB interview.',
      'The written exam has Mathematics (300 marks) and GAT (600 marks). Our NIT Hamirpur-trained faculty owns the maths section with shortcut techniques, while structured GAT classes cover English, GK, Science, and current affairs.',
    ],
    covers: [
      'NDA Mathematics — complete 300-mark syllabus with shortcuts',
      'GAT — English, Physics, Chemistry, GK, History, Geography, Current Affairs',
      'Previous year NDA papers, solved and analyzed',
      'Weekly full mock tests on UPSC pattern',
      'SSB training — GD, interviews, psychology, personality development',
      'Physical fitness guidance for SSB standards',
    ],
    fee: 'NDA program: typically ₹3,000–₹5,000/month.',
    faqs: [
      { q: 'Is there NDA coaching in Una, HP?', a: 'Yes — Vision Success specializes in NDA coaching in Una. Our NIT Hamirpur faculty covers the complete written NDA Maths syllabus with shortcut techniques and previous year paper practice, plus GAT and SSB training.' },
      { q: 'When can I start NDA preparation?', a: 'Ideally from Class 11, but students who join after Class 12 also clear the exam. If you are under 19.5 years, it is not too late.' },
      { q: 'Do you also prepare for the SSB interview?', a: 'Yes — SSB is 50% of the final selection, so every week includes group discussions, public speaking, and personality development.' },
      { q: 'Can girls join NDA coaching?', a: 'Absolutely. NDA has been open to women since 2021 and we proudly train girl cadets for both the written exam and SSB.' },
      { q: 'Is there an online NDA course?', a: 'Yes — our Online NDA Mathematics Course (₹5,000/year) is launching for students across India. See the Online NDA Course page for details.' },
    ],
    related: [
      { href: '/courses/nda', label: 'Full NDA Program — Schedule & Fun Facts' },
      { href: '/maths-coaching-una', label: 'Maths Coaching in Una' },
      { href: '/online-nda-course', label: 'Online NDA Maths Course (Pan-India)' },
    ],
  },
  {
    slug: 'jee-coaching-una',
    seoTitle: 'JEE Coaching in Una HP | Maths Physics Chemistry',
    metaDescription:
      'JEE Mains coaching in Una, HP — PCM by NIT Hamirpur faculty. Concept-first teaching, weekly mocks, board integration. Small batches. Free demo class.',
    h1: 'JEE Mains Coaching in Una, Himachal Pradesh',
    emoji: '⚗️',
    courseName: 'JEE Coaching in Una — Mains & Advanced Foundation',
    intro: [
      'You do not need to move to Kota to prepare seriously for JEE. Our JEE coaching in Una delivers concept-first Physics, Chemistry, and Mathematics teaching by an NIT Hamirpur alumnus — someone who has cleared this path himself.',
      'JEE Mains runs twice a year and only your best score counts. Our program integrates board preparation, weekly JEE-pattern mocks, and daily doubt sessions in small batches of maximum 15 students.',
    ],
    covers: [
      'Physics, Chemistry, Mathematics — full JEE Mains syllabus',
      'Concept-first teaching with graded problem sets',
      'Weekly JEE-pattern mock tests with percentile tracking',
      'Previous year paper analysis, chapter-wise',
      'Board + JEE integrated preparation (75% criterion safe)',
      'Daily doubt sessions — no doubt goes home',
    ],
    fee: 'JEE program: typically ₹3,000–₹5,000/month.',
    faqs: [
      { q: 'Is JEE coaching available in Una?', a: 'Yes — Vision Success offers JEE Mains coaching in Una covering Physics, Chemistry, and Maths, taught by an NIT Hamirpur alumnus.' },
      { q: 'Can small-town students really crack JEE?', a: 'Every year students from small towns outrank metro students. What matters is quality guidance and consistency — both are our job.' },
      { q: 'Do you prepare for boards alongside JEE?', a: 'Yes — the syllabus overlaps heavily. We schedule board-style practice alongside JEE problem solving so your Class 12 marks stay safe.' },
      { q: 'Is there a dropper batch for JEE?', a: 'Yes, a dedicated full-day dropper batch runs in the morning hours with extra mocks and mentoring.' },
      { q: 'What is the JEE coaching fee in Una?', a: 'Typically ₹3,000–₹5,000/month — and always negotiable based on your situation. Talk to us first.' },
    ],
    related: [
      { href: '/courses/jee', label: 'Full JEE Program — Schedule & Fun Facts' },
      { href: '/maths-coaching-una', label: 'Maths Coaching in Una' },
      { href: '/physics-coaching-una', label: 'Physics Coaching in Una' },
      { href: '/chemistry-coaching-una', label: 'Chemistry Coaching in Una' },
    ],
  },
  {
    slug: 'neet-coaching-una',
    seoTitle: 'NEET Coaching in Una HP | Biology Chemistry Physics',
    metaDescription:
      'NEET coaching in Una, HP — Biology, Chemistry, Physics with NCERT deep-dive, 5000+ question bank, weekly mocks. 50+ MBBS admissions. Free demo class.',
    h1: 'NEET Coaching in Una, Himachal Pradesh',
    emoji: '🩺',
    courseName: 'NEET Coaching in Una — Medical Entrance',
    intro: [
      'From Una to a white coat — our NEET coaching in Una has helped 50+ students reach MBBS seats. The method is simple and relentless: NCERT mastery, a 5000+ question bank, and weekly NEET-pattern mocks under real exam conditions.',
      'Biology (360 marks), Chemistry, and Physics are each taught the way NEET actually tests them — with special focus on the NCERT lines and diagrams that most questions come from.',
    ],
    covers: [
      'Biology — NCERT line-by-line + diagram-based teaching',
      'Chemistry — Physical, Organic, Inorganic for NEET',
      'Physics — conceptual clarity at NEET level',
      '5000+ curated question bank',
      'Weekly NEET-pattern OMR mock tests',
      'Counselling guidance after results — AIQ, state quota, college choice',
    ],
    fee: 'NEET program: typically ₹3,000–₹5,000/month.',
    faqs: [
      { q: 'Is NEET coaching available in Una?', a: 'Yes — Vision Success offers complete NEET coaching in Una covering Biology, Chemistry, and Physics for Class 11, 12, and droppers.' },
      { q: 'Is NCERT enough for NEET?', a: 'For Biology, NCERT is the core — most questions map directly to it. We layer a 5000+ question bank and previous-year papers on top so you can apply what you learn.' },
      { q: 'Do you have a NEET dropper batch?', a: 'Yes — a dedicated full-day dropper batch with its own fast-paced schedule, extra mocks, and mentoring.' },
      { q: 'What happens after I clear NEET?', a: 'We guide you through counselling — AIQ vs state quota, college selection, and documentation — all the way to admission.' },
      { q: 'What is the NEET coaching fee in Una?', a: 'Typically ₹3,000–₹5,000/month, always negotiable based on your family situation. Fees are never a barrier here.' },
    ],
    related: [
      { href: '/courses/neet', label: 'Full NEET Program — Schedule & Fun Facts' },
      { href: '/biology-coaching-una', label: 'Biology Coaching in Una' },
      { href: '/chemistry-coaching-una', label: 'Chemistry Coaching in Una' },
      { href: '/physics-coaching-una', label: 'Physics Coaching in Una' },
    ],
  },
  {
    slug: 'cuet-coaching-una',
    seoTitle: 'CUET Coaching in Una HP | Domain + General Test',
    metaDescription:
      'CUET coaching in Una for DU, BHU, JNU admission — domain subjects (PCM/PCB) + General Test. NCERT-based teaching, mock tests. Free demo class available.',
    h1: 'CUET Coaching in Una — Top University Admission Preparation',
    emoji: '🏛️',
    courseName: 'CUET Coaching in Una — Domain + General Test',
    intro: [
      'One exam now decides admission to Delhi University, BHU, JNU, and 250+ universities — CUET. Our CUET coaching in Una prepares you for domain subjects (Maths, Physics, Chemistry, Biology) and the General Test, using the same NCERT syllabus as your Class 12 boards.',
      'That means one smart preparation lifts both your board marks and your university admission chances at the same time.',
    ],
    covers: [
      'Domain subjects — Maths, Physics, Chemistry, Biology',
      'General Test — quantitative aptitude, reasoning, GK',
      'Language section preparation',
      'CUET-pattern computer-based mock tests',
      'University & course selection guidance (DU, BHU, JNU and more)',
      'Combined board + CUET preparation',
    ],
    fee: 'CUET program: typically ₹2,000–₹3,500/month.',
    faqs: [
      { q: 'Do you offer CUET coaching near Una?', a: 'Yes — Vision Success in Una provides CUET coaching for domain subjects (Maths, Physics, Chemistry, Biology) and the General Test. Ideal for students targeting top central universities.' },
      { q: 'What is CUET and who should take it?', a: 'CUET is the Common University Entrance Test — the gateway to DU, BHU, JNU and 250+ universities. Any Class 12 student planning a university degree should seriously consider it.' },
      { q: 'Can I prepare for CUET with my boards?', a: 'Yes — CUET domain subjects use the Class 12 NCERT syllabus, so our combined preparation improves both scores at once.' },
      { q: 'Which subjects should I pick for CUET?', a: 'It depends on your target course. We guide every student on the right domain-subject combination for their target university and degree.' },
      { q: 'Is CUET coaching common in Himachal?', a: 'Very few institutes in the region offer structured CUET preparation — we cover domain subjects, the General Test, and mocks under one roof.' },
    ],
    related: [
      { href: '/courses/cuet', label: 'Full CUET Program — Schedule & Details' },
      { href: '/maths-coaching-una', label: 'Maths Coaching in Una' },
      { href: '/physics-coaching-una', label: 'Physics Coaching in Una' },
    ],
  },
  {
    slug: 'merchant-navy-coaching-una',
    seoTitle: 'Merchant Navy Coaching Una HP | IMU CET Prep',
    metaDescription:
      'Merchant Navy (IMU CET) coaching in Una, HP — Maths, Physics, English & aptitude. One of the few institutes in Himachal offering this. Free counseling session.',
    h1: 'Merchant Navy Coaching in Una — IMU CET Preparation',
    emoji: '🚢',
    courseName: 'Merchant Navy Coaching in Una — IMU CET',
    intro: [
      'A career that pays ₹1 lakh+ per month, shows you the world, and starts right after Class 12 — that is the Merchant Navy. And almost nobody in Himachal Pradesh coaches for it. Vision Success is one of the very few institutes in HP offering IMU CET preparation.',
      'Our merchant navy coaching in Una covers the complete IMU CET syllabus — Mathematics, Physics, Chemistry, English, and General Aptitude — plus honest career counselling about eligibility, medical standards, sponsorships, and life at sea.',
    ],
    covers: [
      'IMU CET Mathematics — complete syllabus',
      'Physics & Chemistry at IMU CET level',
      'English — grammar, vocabulary, comprehension',
      'General Aptitude & reasoning',
      'IMU CET pattern mock tests, timed',
      'Career guidance — courses, colleges, sponsorships, medical standards',
    ],
    fee: 'IMU CET program: typically ₹3,000–₹5,000/month.',
    faqs: [
      { q: 'Is Merchant Navy coaching available in Una?', a: 'Yes — Vision Success offers IMU CET Merchant Navy entrance coaching in Una, HP. We prepare students in Maths, Physics, English, and aptitude — one of very few institutes in Himachal Pradesh offering this.' },
      { q: 'What is IMU CET?', a: 'IMU CET is the entrance exam of the Indian Maritime University — the gateway to B.Sc Nautical Science, Marine Engineering, and other courses leading to a Merchant Navy career.' },
      { q: 'What is the eligibility for Merchant Navy?', a: 'Class 12 with PCM (typically 60%+ in PCM, 50% in English), good eyesight, and medical fitness. We guide you through the exact current criteria.' },
      { q: 'How much do Merchant Navy officers earn?', a: 'Officers can earn ₹1 lakh+ per month early in their careers, with international postings and months of paid leave. We give you the honest full picture in counselling.' },
      { q: 'Why choose Vision Success for this?', a: 'Because structured IMU CET coaching barely exists in HP — students otherwise travel to Chandigarh or Delhi. We bring it to Una with our NIT-trained maths and physics faculty.' },
    ],
    related: [
      { href: '/courses/merchant-navy', label: 'Full Merchant Navy Program' },
      { href: '/maths-coaching-una', label: 'Maths Coaching in Una' },
      { href: '/physics-coaching-una', label: 'Physics Coaching in Una' },
    ],
  },
  {
    slug: 'class-10-coaching-una',
    seoTitle: 'Class 10 Coaching in Una HP | CBSE & HP Board',
    metaDescription:
      'Class 10 coaching in Una — Maths, Science, English for CBSE & HP Board. Small batches, weekly tests, parent updates. ₹1,500–2,000/month. Free demo class.',
    h1: 'Class 10 Coaching in Una — CBSE and HP Board',
    emoji: '📘',
    courseName: 'Class 10 Coaching in Una — CBSE & HP Board',
    intro: [
      'Class 10 is the first board exam of a student\'s life — and the result shapes stream selection, confidence, and everything after. Our Class 10 coaching in Una covers Maths, Science, and English for both CBSE and HP Board with weekly tests and parent progress reports.',
      'We focus on strong basics because Class 10 concepts are the foundation of everything in Class 11, 12, JEE, NEET, and NDA.',
    ],
    covers: [
      'Mathematics — complete board syllabus + basics repair',
      'Science — Physics, Chemistry, Biology portions',
      'English — grammar, writing skills, literature',
      'Weekly chapter tests + board sample papers',
      'Previous year board papers practice',
      'Parent progress reports every month',
    ],
    fee: 'Class 10: ₹1,500–₹2,000/month.',
    faqs: [
      { q: 'Is Class 10 coaching available in Una?', a: 'Yes — Vision Success offers Class 10 coaching for both CBSE and HP Board (HPBOSE) students in Una, covering Maths, Science, and English.' },
      { q: 'What is the fee for Class 10 coaching?', a: 'Typically ₹1,500–₹2,000/month — and always negotiable based on your family situation.' },
      { q: 'How do you handle weak students?', a: 'Small batches (max 15) mean we find the exact gaps — even from earlier classes — and fix them with extra practice and doubt sessions.' },
      { q: 'Do parents get progress updates?', a: 'Yes — weekly test scores and monthly progress reports keep parents fully in the loop. No surprises on result day.' },
      { q: 'Does Class 10 coaching help for JEE/NEET later?', a: 'Hugely. Class 10 concepts are the base of nearly half of entrance exam topics. Students who build basics now find Class 11 far easier.' },
    ],
    related: [
      { href: '/class-11-coaching-una', label: 'Class 11 Science Coaching' },
      { href: '/maths-coaching-una', label: 'Maths Coaching in Una' },
      { href: '/hp-board-coaching-una', label: 'HP Board Coaching in Una' },
    ],
  },
  {
    slug: 'class-11-coaching-una',
    seoTitle: 'Class 11 Science Coaching in Una HP | PCM & PCB',
    metaDescription:
      'Class 11 Science coaching in Una — Physics, Chemistry, Maths, Biology for CBSE & HP Board with JEE/NEET foundation. Small batches. Free demo class available.',
    h1: 'Class 11 Science Coaching in Una — Physics, Chemistry, Maths, Biology',
    emoji: '📗',
    courseName: 'Class 11 Science Coaching in Una — PCM & PCB',
    intro: [
      'Class 11 is the biggest academic jump a student ever faces — the syllabus triples and the concepts deepen. Our Class 11 Science coaching in Una supports both PCM and PCB streams with Physics, Chemistry, Maths, and Biology taught from absolute fundamentals.',
      'This is also exactly when JEE and NEET preparation should begin — so our teaching quietly builds entrance-level thinking alongside school work.',
    ],
    covers: [
      'Physics — full Class 11 syllabus, concept-first',
      'Chemistry — Physical, Organic, Inorganic foundations',
      'Mathematics — Algebra, Trigonometry, Coordinate Geometry',
      'Biology — Botany & Zoology with diagrams',
      'JEE/NEET foundation layered on school topics',
      'Weekly tests + homework tracking',
    ],
    fee: 'Class 11 Science: ₹2,000–₹3,500/month.',
    faqs: [
      { q: 'Is Class 11 Science coaching available in Una?', a: 'Yes — we coach Class 11 PCM and PCB students in Una for CBSE and HP Board, with JEE/NEET foundation built in.' },
      { q: 'Why does Class 11 feel so hard?', a: 'The syllabus jump from Class 10 is the steepest in school life. Our concept-first approach and small batches are designed exactly for this transition.' },
      { q: 'Should JEE/NEET prep start in Class 11?', a: 'Yes — two years of steady preparation beats one year of panic. Class 11 is the ideal starting point, and our teaching integrates it naturally.' },
      { q: 'Can I take only some subjects?', a: 'Yes — join for the subjects you need. Many students take Maths + Physics or Biology + Chemistry combinations.' },
      { q: 'What are the timings for Class 11 batches?', a: 'After-school evening batches, adjusted each term around school hours. WhatsApp us for the current timetable.' },
    ],
    related: [
      { href: '/physics-coaching-una', label: 'Physics Coaching in Una' },
      { href: '/chemistry-coaching-una', label: 'Chemistry Coaching in Una' },
      { href: '/biology-coaching-una', label: 'Biology Coaching in Una' },
      { href: '/class-12-coaching-una', label: 'Class 12 Coaching in Una' },
    ],
  },
  {
    slug: 'class-12-coaching-una',
    seoTitle: 'Class 12 Coaching in Una HP | Board + JEE NEET',
    metaDescription:
      'Class 12 Science coaching in Una — boards + JEE/NEET/CUET combined preparation. PCM & PCB, sample papers, weekly tests. Free demo class — call or WhatsApp.',
    h1: 'Class 12 Science Coaching in Una — Board + Competitive Exam Preparation',
    emoji: '📕',
    courseName: 'Class 12 Science Coaching in Una — Board + Entrance',
    intro: [
      'Class 12 is the year everything converges — board exams, JEE, NEET, CUET, and NDA eligibility all depend on these twelve months. Our Class 12 coaching in Una prepares you for boards and entrance exams together, because the syllabus is shared and time is not.',
      'PCM and PCB streams both run in small after-school batches with weekly tests, sample paper marathons, and answer-writing practice for full board marks.',
    ],
    covers: [
      'Physics, Chemistry, Maths, Biology — complete Class 12 syllabus',
      'Board answer-writing + presentation practice',
      'Sample papers and previous year board papers',
      'JEE/NEET/CUET integrated question practice',
      'Pre-board test series with analysis',
      'Weekly doubts + revision cycles before exams',
    ],
    fee: 'Class 12 Science: ₹2,000–₹3,500/month.',
    faqs: [
      { q: 'Is Class 12 coaching available in Una?', a: 'Yes — Vision Success coaches Class 12 PCM and PCB students in Una for CBSE and HP Board, with integrated JEE/NEET/CUET preparation.' },
      { q: 'Can I manage boards and JEE/NEET together?', a: 'Yes — the syllabus overlaps almost entirely. We teach concepts once and train you in both board-style writing and entrance-style problem solving.' },
      { q: 'Do board marks still matter?', a: 'Very much — IIT/NIT admission needs 75% in boards, CUET works alongside board marks, and good marks open every door. We never let boards slip.' },
      { q: 'When should Class 12 students join?', a: 'As early in the academic year as possible — but we also run intensive support for students who join mid-year. Talk to us either way.' },
      { q: 'Is there crash-course support before boards?', a: 'Yes — see our 45-Day Board Crash Course that runs before board exams, with rapid full-syllabus revision.' },
    ],
    related: [
      { href: '/class-11-coaching-una', label: 'Class 11 Science Coaching' },
      { href: '/jee-coaching-una', label: 'JEE Coaching in Una' },
      { href: '/neet-coaching-una', label: 'NEET Coaching in Una' },
      { href: '/board-crash-course-una', label: '45-Day Board Crash Course' },
    ],
  },
  {
    slug: 'coaching-in-una',
    seoTitle: 'Best Coaching Institute in Una HP | All Subjects',
    metaDescription:
      'Vision Success — best coaching institute in Una, HP. Maths, Physics, Chemistry, Biology for Class 10–12, JEE, NEET, NDA, CUET, Merchant Navy. Free demo class.',
    h1: 'Best Coaching Institute in Una, Himachal Pradesh',
    emoji: '🏆',
    courseName: null, // hub page — LocalBusiness focus, no Course schema
    intro: [
      'If you are searching for a coaching institute in Una that treats your child like a mission and not a roll number — welcome to Vision Success. We coach every science subject and every major exam a student in Una district needs, under one roof, in small batches of maximum 15.',
      'Founded by an NIT Hamirpur alumnus, Vision Success has produced 7+ NDA officers, 50+ MBBS admissions, and 90%+ board results. Students join us from Una, Amb, Bangana, Haroli, Daulatpur, and Mehatpur.',
    ],
    covers: [
      'Subjects — Mathematics, Physics, Chemistry, Biology, English',
      'Classes — 9, 10, 11, 12 (CBSE + HP Board)',
      'NDA — written exam + SSB (our flagship)',
      'JEE Mains & Advanced — engineering entrance',
      'NEET — medical entrance',
      'CUET — central university admission',
      'Merchant Navy — IMU CET (rare in HP)',
      'Board crash courses before exam season',
    ],
    fee: 'Class 10: ₹1,500–2,000/mo · Class 11–12: ₹2,000–3,500/mo · JEE/NEET/NDA: ₹3,000–5,000/mo.',
    faqs: [
      { q: 'Which is the best coaching institute in Una?', a: 'Vision Success Coaching Institute is Una\'s leading institute for NDA, JEE, NEET, CUET, and Class 9–12 coaching — with NIT Hamirpur faculty, small batches, a 4.9★ Google rating, and results to show.' },
      { q: 'Which subjects do you teach?', a: 'Mathematics, Physics, Chemistry, Biology, and English — for Class 9 to 12, plus complete preparation for NDA, JEE, NEET, CUET, and Merchant Navy (IMU CET).' },
      { q: 'What are the fees?', a: 'Roughly ₹1,500–₹5,000/month depending on class and course — and always negotiated based on your ability. No capable student is ever turned away for money.' },
      { q: 'Do students from Amb, Bangana, Haroli come to Vision Success?', a: 'Yes — we have students from Una, Amb, Bangana, Haroli, Daulatpur, and Mehatpur. Students commute easily via HRTC bus; we are near the old bus stand.' },
      { q: 'Is there a free demo class?', a: 'Yes — every new student gets a free demo class. No payment, no obligation. Call or WhatsApp to book.' },
    ],
    related: [
      { href: '/maths-coaching-una', label: 'Maths Coaching' },
      { href: '/physics-coaching-una', label: 'Physics Coaching' },
      { href: '/chemistry-coaching-una', label: 'Chemistry Coaching' },
      { href: '/biology-coaching-una', label: 'Biology Coaching' },
      { href: '/nda-coaching-una', label: 'NDA Coaching' },
      { href: '/jee-coaching-una', label: 'JEE Coaching' },
      { href: '/neet-coaching-una', label: 'NEET Coaching' },
      { href: '/cuet-coaching-una', label: 'CUET Coaching' },
      { href: '/merchant-navy-coaching-una', label: 'Merchant Navy Coaching' },
      { href: '/class-10-coaching-una', label: 'Class 10 Coaching' },
      { href: '/class-11-coaching-una', label: 'Class 11 Coaching' },
      { href: '/class-12-coaching-una', label: 'Class 12 Coaching' },
    ],
  },
  {
    slug: 'tuition-una',
    seoTitle: 'Best Tuition Classes in Una HP | All Subjects',
    metaDescription:
      'Tuition classes in Una for Maths, Science, Physics, Chemistry, Biology — Class 9 to 12, CBSE & HP Board. Small batches, weekly tests. Free demo class today.',
    h1: 'Tuition Classes in Una, Himachal Pradesh — All Subjects',
    emoji: '✏️',
    courseName: null,
    intro: [
      'Searching for reliable tuition in Una? Vision Success runs structured, small-batch tuition classes for Maths, Physics, Chemistry, Biology, and Science — Class 9 through 12, for both CBSE and HP Board.',
      'This is not casual tuition — every batch follows a plan: concept classes, weekly tests, homework tracking, and monthly parent updates, taught under the guidance of an NIT Hamirpur alumnus.',
    ],
    covers: [
      'Class 9–10 — Maths, Science, English tuition',
      'Class 11–12 — Physics, Chemistry, Maths, Biology tuition',
      'CBSE and HP Board (HPBOSE) both covered',
      'Weekly chapter tests + board sample papers',
      'Homework and progress tracking',
      'Doubt sessions every week',
    ],
    fee: 'From ₹1,500/month (Class 9–10) to ₹3,500/month (Class 11–12), per subject group.',
    faqs: [
      { q: 'Where can I find good tuition classes in Una?', a: 'Vision Success Coaching Institute near the old bus stand in Una runs structured tuition for Class 9–12 in all science subjects and maths, with a 4.9★ Google rating.' },
      { q: 'What makes this different from home tuition?', a: 'Structured syllabus coverage, weekly tests, peer learning in small batches, and NIT-trained faculty — at a fee comparable to home tuition.' },
      { q: 'Which boards do you cover?', a: 'Both CBSE and HP Board (HPBOSE), with board-specific sample paper practice before exams.' },
      { q: 'Can I join for one subject only?', a: 'Yes — single-subject tuition is available for Maths, Physics, Chemistry, or Biology.' },
      { q: 'Is there a free trial?', a: 'Yes — a free demo class before you commit. Call or WhatsApp us to schedule it.' },
    ],
    related: [
      { href: '/maths-coaching-una', label: 'Maths Tuition in Una' },
      { href: '/science-coaching-una', label: 'Science Coaching in Una' },
      { href: '/class-10-coaching-una', label: 'Class 10 Tuition in Una' },
    ],
  },
  {
    slug: 'science-coaching-una',
    seoTitle: 'Science Coaching in Una HP | Physics Chem Biology',
    metaDescription:
      'Science coaching in Una — Physics, Chemistry, Biology for Class 9–12, CBSE & HP Board, with NEET/JEE foundation. Small batches. Free demo class available.',
    h1: 'Science Coaching in Una — Physics, Chemistry, Biology',
    emoji: '🔬',
    courseName: 'Science Coaching in Una — PCB/PCM',
    intro: [
      'Science is not a subject to memorize — it is a way of thinking. Our science coaching in Una covers Physics, Chemistry, and Biology for Class 9 to 12 with experiments-first explanations, diagrams, and weekly practice tests.',
      'Whether your goal is board excellence, NEET, or JEE, the foundation is the same: concepts taught clearly, in small batches, by faculty who love the subject.',
    ],
    covers: [
      'Class 9–10 Science — full syllabus, CBSE & HP Board',
      'Class 11–12 Physics, Chemistry, Biology',
      'Diagram-based Biology teaching',
      'Numerical practice for Physics & Chemistry',
      'NEET/JEE foundation integrated',
      'Weekly tests + sample papers',
    ],
    fee: 'Class 9–10: ₹1,500–₹2,000/month · Class 11–12: ₹2,000–₹3,500/month.',
    faqs: [
      { q: 'Is science coaching available in Una?', a: 'Yes — Vision Success offers science coaching (Physics, Chemistry, Biology) for Class 9 to 12 in Una, for CBSE and HP Board.' },
      { q: 'Do you cover PCB and PCM both?', a: 'Yes — both streams run in dedicated batches with subject-specific teaching.' },
      { q: 'Is this good preparation for NEET or JEE?', a: 'Yes — our science teaching builds entrance-level thinking on top of board topics, so the transition to NEET/JEE prep is natural.' },
      { q: 'How are practicals and diagrams handled?', a: 'Biology is taught diagram-first and physics/chemistry concepts are demonstrated wherever possible — because seeing beats cramming.' },
      { q: 'What are the batch timings?', a: 'After-school evening batches for each class group. WhatsApp us for the current timetable.' },
    ],
    related: [
      { href: '/physics-coaching-una', label: 'Physics Coaching in Una' },
      { href: '/chemistry-coaching-una', label: 'Chemistry Coaching in Una' },
      { href: '/biology-coaching-una', label: 'Biology Coaching in Una' },
    ],
  },
  {
    slug: 'hp-board-coaching-una',
    seoTitle: 'HP Board Coaching in Una | HPBOSE Class 10 & 12',
    metaDescription:
      'HP Board (HPBOSE) coaching in Una for Class 10 & 12 — Maths, Science, Physics, Chemistry, Biology. Board-specific sample papers, weekly tests. Free demo.',
    h1: 'HP Board Coaching in Una — HPBOSE Class 10 and Class 12',
    emoji: '🏔️',
    courseName: 'HP Board (HPBOSE) Coaching in Una — Class 10 & 12',
    intro: [
      'HPBOSE exams have their own paper style, marking scheme, and question patterns — and preparing with generic CBSE material leaves marks on the table. Our HP Board coaching in Una is tuned specifically for HPBOSE Class 10 and Class 12 students.',
      'We use HPBOSE sample papers, previous year board papers, and answer-writing formats that HP Board examiners actually reward.',
    ],
    covers: [
      'HPBOSE Class 10 — Maths, Science, English',
      'HPBOSE Class 12 — Physics, Chemistry, Maths, Biology',
      'HP Board previous year papers, solved',
      'HPBOSE-specific answer-writing practice',
      'Pre-board test series on HP Board pattern',
      'Revision marathons before board exams',
    ],
    fee: 'Class 10: ₹1,500–₹2,000/month · Class 12: ₹2,000–₹3,500/month.',
    faqs: [
      { q: 'Do you coach HP Board (HPBOSE) students in Una?', a: 'Yes — HP Board students are a big part of Vision Success. Our teaching, tests, and sample papers are tuned to HPBOSE patterns for Class 10 and 12.' },
      { q: 'Is HPBOSE different from CBSE preparation?', a: 'The concepts are the same but paper style and marking differ. We train you on HPBOSE previous year papers and answer formats specifically.' },
      { q: 'Can HP Board students crack JEE/NEET?', a: 'Absolutely — entrance exams are NCERT-based and board-neutral. Many of our HP Board students go on to JEE, NEET, and NDA success.' },
      { q: 'Do you have HPBOSE sample papers?', a: 'Yes — we maintain a full bank of HPBOSE sample papers and previous year papers for practice and pre-boards.' },
      { q: 'When should HP Board students join?', a: 'Ideally at the start of the academic year, but mid-year joiners get catch-up support. The 45-day crash course also runs before boards.' },
    ],
    related: [
      { href: '/class-10-coaching-una', label: 'Class 10 Coaching in Una' },
      { href: '/class-12-coaching-una', label: 'Class 12 Coaching in Una' },
      { href: '/board-crash-course-una', label: '45-Day Board Crash Course' },
    ],
  },
  {
    slug: 'board-crash-course-una',
    seoTitle: '45-Day Board Crash Course Una | Class 10 & 12',
    metaDescription:
      '45-day board exam crash course in Una for Class 10 & 12 (CBSE + HP Board) — ₹5,000 total. Full syllabus rapid revision, sample papers, daily tests. Seats limited.',
    h1: '45-Day Board Crash Course in Una — Class 10 & 12',
    emoji: '🚀',
    courseName: '45-Day Board Crash Course — Class 10 & 12',
    coursePrice: '5000',
    intro: [
      'Board exams around the corner and the syllabus still feels like a mountain? Our 45-day board crash course in Una compresses the complete Class 10 and Class 12 syllabus into a rapid, ruthless revision sprint — starting December 8, before board season.',
      'For a flat ₹5,000, you get daily classes, daily tests, full sample paper practice, and answer-writing training for CBSE and HP Board. Seats are limited to keep batches small.',
    ],
    covers: [
      'Complete syllabus rapid revision — all subjects',
      'Daily practice tests with same-day analysis',
      'Board sample papers + previous year papers',
      'Answer-writing and presentation training',
      'Important questions & expected-question banks',
      'Doubt-clearing sessions every day',
    ],
    fee: 'Flat ₹5,000 for the complete 45-day crash course. Starts December 8 — seats limited.',
    faqs: [
      { q: 'What is the 45-day board crash course?', a: 'A rapid full-syllabus revision program for Class 10 and 12 board exams (CBSE + HP Board), running daily for 45 days before board season with tests and sample papers.' },
      { q: 'How much does the crash course cost?', a: 'A flat ₹5,000 for the complete 45-day program — daily classes, tests, and materials included.' },
      { q: 'When does the crash course start?', a: 'December 8, before the board exam season. Enrollment opens in October — WhatsApp us to reserve a seat early, batches are limited.' },
      { q: 'Is a crash course enough to pass boards?', a: 'A crash course cannot replace a year of study, but it can massively sharpen what you know — targeted revision, expected questions, and exam-writing technique often lift results by a full grade.' },
      { q: 'Which subjects are covered?', a: 'All main subjects — Maths, Science (Physics, Chemistry, Biology), and English — for Class 10 and Class 12, CBSE and HPBOSE.' },
    ],
    related: [
      { href: '/class-10-coaching-una', label: 'Class 10 Coaching in Una' },
      { href: '/class-12-coaching-una', label: 'Class 12 Coaching in Una' },
      { href: '/hp-board-coaching-una', label: 'HP Board Coaching in Una' },
    ],
  },
  {
    slug: 'online-nda-course',
    seoTitle: 'Online NDA Maths Course India | ₹5,000/year',
    metaDescription:
      'Online NDA Mathematics course for all of India — complete 300-mark written syllabus by NIT Hamirpur faculty. ₹5,000/year. Launching January 2027 — join waitlist.',
    h1: 'Online NDA Mathematics Course — Pan-India, ₹5,000/year',
    emoji: '🇮🇳',
    courseName: 'Online NDA Mathematics Course — Pan India',
    coursePrice: '5000',
    comingSoon: true,
    intro: [
      'The NDA written exam gives Mathematics 300 marks — and maths is where most aspirants lose their selection. Our Online NDA Mathematics Course brings Vision Success\'s proven NDA maths training to every aspirant in India, for just ₹5,000 a year.',
      'Taught by the same NIT Hamirpur faculty that has trained 7+ serving officers from a small town in Himachal — now available wherever you are. Launching January 2027.',
    ],
    covers: [
      'Complete NDA Maths syllabus — all 300 marks covered',
      'Recorded concept lectures + live doubt sessions',
      'Shortcut techniques for UPSC-speed solving',
      'Chapter-wise tests + full-length mocks',
      'Previous year NDA papers, solved on video',
      'WhatsApp doubt support',
    ],
    fee: '₹5,000 per year — full course access. Launching January 2027.',
    faqs: [
      { q: 'What is the Online NDA Maths Course?', a: 'A complete online preparation course for the 300-mark NDA written exam Mathematics section — lectures, tests, mocks, and doubt support — accessible from anywhere in India.' },
      { q: 'How much does it cost?', a: '₹5,000 for a full year of access — a fraction of offline NDA coaching costs.' },
      { q: 'When does the course launch?', a: 'January 2027. Join the waitlist on WhatsApp now and get launch-day access plus early-bird materials.' },
      { q: 'Who teaches the course?', a: 'The NIT Hamirpur-trained faculty of Vision Success Coaching Institute, Una — the same teaching that has produced 7+ serving officers.' },
      { q: 'Is online preparation enough for NDA Maths?', a: 'For the written exam maths section — yes, with discipline. The course includes tests and doubt support to keep you accountable. SSB preparation is separate and we guide you on that too.' },
    ],
    related: [
      { href: '/nda-coaching-una', label: 'NDA Coaching in Una (Offline)' },
      { href: '/courses/nda', label: 'Full NDA Program — Details' },
      { href: '/maths-coaching-una', label: 'Maths Coaching in Una' },
    ],
  },
]

export const WHY_US = WHY_US_BASE
export const FEES_NOTE = FEE_NOTE
export const getSeoPage = (slug) => SEO_PAGES.find((p) => p.slug === slug)
